name: main

on:
  push:
    branches: [ "main" ]

jobs:

  build-cli:
    strategy:
      matrix:
        host:
          - ubuntu-latest
          - macos-latest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v19
      - run: nix build .
